/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/design/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/brandable-ui-library/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: 'var(--font-family-headline)',
        title: 'var(--font-family-title)',
        subtitle: 'var(--font-family-subtitle)',
        body: 'var(--font-family-body)',
        caption: 'var(--font-family-caption)',
      },
      fontSize: {
        xxs: 'var(--font-size-xxs)',
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
      },
      colors: {
        'primary-dark': 'var(--color-primary-dark)',
        primary: 'var(--color-primary)',
        'primary-light': 'var(--color-primary-light)',
        'secondary-dark': 'var(--color-secondary-dark)',
        secondary: 'var(--color-secondary)',
        'secondary-light': 'var(--color-secondary-light)',
        'tertiary-dark': 'var(--color-tertiary-dark)',
        tertiary: 'var(--color-tertiary)',
        'tertiary-light': 'var(--color-tertiary-light)',
        'accent-dark': 'var(--color-accent-dark)',
        accent: 'var(--color-accent)',
        'accent-light': 'var(--color-accent-light)',
        'ink-dark': 'var(--color-ink-dark)',
        ink: 'var(--color-ink)',
        'ink-light': 'var(--color-ink-light)',
        'paper-dark': 'var(--color-paper-dark)',
        paper: 'var(--color-paper)',
        'paper-light': 'var(--color-paper-light)',
      },
      boxShadow: {
        card: 'var(--card-shadow)',
      },
    },
  },
  darkMode: 'class',
  plugins: [],
}
